const espnLogoBase = "https://a.espncdn.com/i/teamlogos";
const flagLogoBase = "https://flagcdn.com/w160";

const countryFlagCodes: Record<string, string> = {
  algeria: "dz",
  argentina: "ar",
  australia: "au",
  austria: "at",
  belgium: "be",
  bolivia: "bo",
  brazil: "br",
  cameroon: "cm",
  canada: "ca",
  chile: "cl",
  china: "cn",
  colombia: "co",
  "costa rica": "cr",
  "cote d ivoire": "ci",
  "ivory coast": "ci",
  croatia: "hr",
  denmark: "dk",
  ecuador: "ec",
  egypt: "eg",
  england: "gb-eng",
  france: "fr",
  germany: "de",
  ghana: "gh",
  greece: "gr",
  guatemala: "gt",
  haiti: "ht",
  honduras: "hn",
  hungary: "hu",
  iceland: "is",
  iran: "ir",
  iraq: "iq",
  israel: "il",
  italy: "it",
  jamaica: "jm",
  japan: "jp",
  jordan: "jo",
  "korea republic": "kr",
  "south korea": "kr",
  mali: "ml",
  mexico: "mx",
  morocco: "ma",
  netherlands: "nl",
  "new zealand": "nz",
  nigeria: "ng",
  norway: "no",
  panama: "pa",
  paraguay: "py",
  peru: "pe",
  poland: "pl",
  portugal: "pt",
  qatar: "qa",
  romania: "ro",
  "saudi arabia": "sa",
  scotland: "gb-sct",
  senegal: "sn",
  serbia: "rs",
  slovakia: "sk",
  slovenia: "si",
  "south africa": "za",
  spain: "es",
  sweden: "se",
  switzerland: "ch",
  tunisia: "tn",
  turkey: "tr",
  turkiye: "tr",
  ukraine: "ua",
  "united arab emirates": "ae",
  "united states": "us",
  usa: "us",
  uruguay: "uy",
  uzbekistan: "uz",
  venezuela: "ve",
  wales: "gb-wls"
};

const teamLogoMap: Record<string, { league: string; code: string }> = {
  "arizona cardinals": { league: "nfl", code: "ari" },
  "atlanta falcons": { league: "nfl", code: "atl" },
  "baltimore ravens": { league: "nfl", code: "bal" },
  "buffalo bills": { league: "nfl", code: "buf" },
  "carolina panthers": { league: "nfl", code: "car" },
  "chicago bears": { league: "nfl", code: "chi" },
  "cincinnati bengals": { league: "nfl", code: "cin" },
  "cleveland browns": { league: "nfl", code: "cle" },
  "dallas cowboys": { league: "nfl", code: "dal" },
  "denver broncos": { league: "nfl", code: "den" },
  "detroit lions": { league: "nfl", code: "det" },
  "green bay packers": { league: "nfl", code: "gb" },
  "houston texans": { league: "nfl", code: "hou" },
  "indianapolis colts": { league: "nfl", code: "ind" },
  "jacksonville jaguars": { league: "nfl", code: "jax" },
  "kansas city chiefs": { league: "nfl", code: "kc" },
  "las vegas raiders": { league: "nfl", code: "lv" },
  "los angeles chargers": { league: "nfl", code: "lac" },
  "los angeles rams": { league: "nfl", code: "lar" },
  "miami dolphins": { league: "nfl", code: "mia" },
  "minnesota vikings": { league: "nfl", code: "min" },
  "new england patriots": { league: "nfl", code: "ne" },
  "new orleans saints": { league: "nfl", code: "no" },
  "new york giants": { league: "nfl", code: "nyg" },
  "new york jets": { league: "nfl", code: "nyj" },
  "philadelphia eagles": { league: "nfl", code: "phi" },
  "pittsburgh steelers": { league: "nfl", code: "pit" },
  "san francisco 49ers": { league: "nfl", code: "sf" },
  "seattle seahawks": { league: "nfl", code: "sea" },
  "tampa bay buccaneers": { league: "nfl", code: "tb" },
  "tennessee titans": { league: "nfl", code: "ten" },
  "washington commanders": { league: "nfl", code: "wsh" },

  "atlanta hawks": { league: "nba", code: "atl" },
  "boston celtics": { league: "nba", code: "bos" },
  "brooklyn nets": { league: "nba", code: "bkn" },
  "charlotte hornets": { league: "nba", code: "cha" },
  "chicago bulls": { league: "nba", code: "chi" },
  "cleveland cavaliers": { league: "nba", code: "cle" },
  "dallas mavericks": { league: "nba", code: "dal" },
  "denver nuggets": { league: "nba", code: "den" },
  "detroit pistons": { league: "nba", code: "det" },
  "golden state warriors": { league: "nba", code: "gs" },
  "houston rockets": { league: "nba", code: "hou" },
  "indiana pacers": { league: "nba", code: "ind" },
  "los angeles clippers": { league: "nba", code: "lac" },
  "los angeles lakers": { league: "nba", code: "lal" },
  "memphis grizzlies": { league: "nba", code: "mem" },
  "miami heat": { league: "nba", code: "mia" },
  "milwaukee bucks": { league: "nba", code: "mil" },
  "minnesota timberwolves": { league: "nba", code: "min" },
  "new orleans pelicans": { league: "nba", code: "no" },
  "new york knicks": { league: "nba", code: "ny" },
  "oklahoma city thunder": { league: "nba", code: "okc" },
  "orlando magic": { league: "nba", code: "orl" },
  "philadelphia 76ers": { league: "nba", code: "phi" },
  "phoenix suns": { league: "nba", code: "phx" },
  "portland trail blazers": { league: "nba", code: "por" },
  "sacramento kings": { league: "nba", code: "sac" },
  "san antonio spurs": { league: "nba", code: "sa" },
  "toronto raptors": { league: "nba", code: "tor" },
  "utah jazz": { league: "nba", code: "utah" },
  "washington wizards": { league: "nba", code: "wsh" },

  "atlanta dream": { league: "wnba", code: "atl" },
  "chicago sky": { league: "wnba", code: "chi" },
  "connecticut sun": { league: "wnba", code: "conn" },
  "dallas wings": { league: "wnba", code: "dal" },
  "golden state valkyries": { league: "wnba", code: "gs" },
  "indiana fever": { league: "wnba", code: "ind" },
  "las vegas aces": { league: "wnba", code: "lv" },
  "los angeles sparks": { league: "wnba", code: "la" },
  "minnesota lynx": { league: "wnba", code: "min" },
  "new york liberty": { league: "wnba", code: "ny" },
  "phoenix mercury": { league: "wnba", code: "phx" },
  "seattle storm": { league: "wnba", code: "sea" },
  "washington mystics": { league: "wnba", code: "wsh" },

  "arizona diamondbacks": { league: "mlb", code: "ari" },
  "athletics": { league: "mlb", code: "ath" },
  "atlanta braves": { league: "mlb", code: "atl" },
  "baltimore orioles": { league: "mlb", code: "bal" },
  "boston red sox": { league: "mlb", code: "bos" },
  "chicago cubs": { league: "mlb", code: "chc" },
  "chicago white sox": { league: "mlb", code: "chw" },
  "cincinnati reds": { league: "mlb", code: "cin" },
  "cleveland guardians": { league: "mlb", code: "cle" },
  "colorado rockies": { league: "mlb", code: "col" },
  "detroit tigers": { league: "mlb", code: "det" },
  "houston astros": { league: "mlb", code: "hou" },
  "kansas city royals": { league: "mlb", code: "kc" },
  "los angeles angels": { league: "mlb", code: "laa" },
  "los angeles dodgers": { league: "mlb", code: "lad" },
  "miami marlins": { league: "mlb", code: "mia" },
  "milwaukee brewers": { league: "mlb", code: "mil" },
  "minnesota twins": { league: "mlb", code: "min" },
  "new york mets": { league: "mlb", code: "nym" },
  "new york yankees": { league: "mlb", code: "nyy" },
  "philadelphia phillies": { league: "mlb", code: "phi" },
  "pittsburgh pirates": { league: "mlb", code: "pit" },
  "san diego padres": { league: "mlb", code: "sd" },
  "san francisco giants": { league: "mlb", code: "sf" },
  "seattle mariners": { league: "mlb", code: "sea" },
  "st. louis cardinals": { league: "mlb", code: "stl" },
  "tampa bay rays": { league: "mlb", code: "tb" },
  "texas rangers": { league: "mlb", code: "tex" },
  "toronto blue jays": { league: "mlb", code: "tor" },
  "washington nationals": { league: "mlb", code: "wsh" },

  "canada": { league: "soccer", code: "can" },
  "switzerland": { league: "soccer", code: "sui" },
  "united states": { league: "soccer", code: "usa" },
  "mexico": { league: "soccer", code: "mex" },
  "brazil": { league: "soccer", code: "bra" },
  "argentina": { league: "soccer", code: "arg" },
  "france": { league: "soccer", code: "fra" },
  "belgium": { league: "soccer", code: "bel" },
  "england": { league: "soccer", code: "eng" },
  "spain": { league: "soccer", code: "esp" },
  "germany": { league: "soccer", code: "ger" },
  "italy": { league: "soccer", code: "ita" },
  "netherlands": { league: "soccer", code: "ned" },
  "portugal": { league: "soccer", code: "por" }
};

export function teamLogoUrl(name: string) {
  const normalized = normalizeTeamName(name);
  const flagCode = countryFlagCodes[normalized];

  if (flagCode) {
    return `${flagLogoBase}/${flagCode}.png`;
  }

  const match = teamLogoMap[normalized];
  if (!match) return null;

  return `${espnLogoBase}/${match.league}/500/${match.code}.png`;
}

function normalizeTeamName(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9\s.]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
